# Generated by Django 3.2.7 on 2021-10-04 20:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Acessorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_acessorio', models.CharField(max_length=64)),
                ('descricao_acessorio', models.CharField(max_length=256)),
                ('preco_acessorio', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Aluminio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_aluminio', models.CharField(max_length=64)),
                ('descricao_aluminio', models.CharField(max_length=256)),
                ('peso_aluminio', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=128)),
                ('endereco', models.CharField(max_length=128)),
                ('telefone', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Linha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_linha', models.CharField(max_length=64)),
                ('descricao_linha', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_vendedor', models.CharField(max_length=128)),
                ('telefone_vendedor', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Vidro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_vidro', models.CharField(max_length=64)),
                ('descricao_vidro', models.CharField(max_length=256)),
                ('preco_vidro', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_produto', models.CharField(max_length=64)),
                ('descricao_produto', models.CharField(max_length=256)),
                ('acessorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mp_orcamento.acessorio')),
                ('aluminio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mp_orcamento.aluminio')),
                ('linha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mp_orcamento.linha')),
                ('vidro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mp_orcamento.vidro')),
            ],
        ),
        migrations.CreateModel(
            name='Orcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField()),
                ('materia_prima', models.CharField(choices=[('esquadria', 'Esquadria de Alumínio'), ('temperado', 'Vidro Temperado')], max_length=10)),
                ('pintura', models.CharField(choices=[('BR', 'Pintura Branco'), ('PT', 'Pintura Preto'), ('BZ', 'Anodizado Bronze'), ('FC', 'Anodizado Fosco'), ('AM', 'Pintura Amadeirado')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mp_orcamento.cliente')),
                ('linha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mp_orcamento.linha')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mp_orcamento.vendedor')),
            ],
        ),
        migrations.AddField(
            model_name='aluminio',
            name='linha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mp_orcamento.linha'),
        ),
        migrations.AddField(
            model_name='acessorio',
            name='linha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mp_orcamento.linha'),
        ),
    ]
