# Generated by Django 3.2.7 on 2021-10-07 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mp_orcamento', '0002_remove_orcamento_data_hora'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendedor',
            old_name='nome_vendedor',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='vendedor',
            old_name='telefone_vendedor',
            new_name='telefone',
        ),
    ]
