# Generated by Django 3.2.7 on 2021-10-07 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mp_orcamento', '0003_auto_20211007_1707'),
    ]

    operations = [
        migrations.RenameField(
            model_name='acessorio',
            old_name='codigo_acessorio',
            new_name='codigo',
        ),
        migrations.RenameField(
            model_name='acessorio',
            old_name='descricao_acessorio',
            new_name='descricao',
        ),
        migrations.RenameField(
            model_name='acessorio',
            old_name='preco_acessorio',
            new_name='preco',
        ),
        migrations.RenameField(
            model_name='aluminio',
            old_name='codigo_aluminio',
            new_name='codigo',
        ),
        migrations.RenameField(
            model_name='aluminio',
            old_name='descricao_aluminio',
            new_name='descricao',
        ),
        migrations.RenameField(
            model_name='aluminio',
            old_name='peso_aluminio',
            new_name='peso',
        ),
        migrations.RenameField(
            model_name='linha',
            old_name='codigo_linha',
            new_name='codigo',
        ),
        migrations.RenameField(
            model_name='linha',
            old_name='descricao_linha',
            new_name='descricao',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='codigo_produto',
            new_name='codigo',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='descricao_produto',
            new_name='descricao',
        ),
        migrations.RenameField(
            model_name='vidro',
            old_name='codigo_vidro',
            new_name='codigo',
        ),
        migrations.RenameField(
            model_name='vidro',
            old_name='descricao_vidro',
            new_name='descricao',
        ),
        migrations.RenameField(
            model_name='vidro',
            old_name='preco_vidro',
            new_name='preco',
        ),
    ]
