# Generated by Django 3.2.7 on 2021-10-11 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mp_orcamento', '0004_auto_20211007_1726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orcamento',
            name='linha',
        ),
    ]
